server:
  port: 9096



spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cycevents
    username: root
    password: pritam@123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      dialect: org.hibernate.dialect.MySQLDialect




# Mail Configuration



